#!/bin/bash

#export FQDN=migasfree.mydomain.com
export FQDN=$(ip route get 8.8.8.8| grep src| sed 's/.*src \(.*\)$/\1/g' | cut -d ' ' -f 1)

export MIGASFREE_VERSION_DB=0.5

export MIGASFREE_VERSION=4.22
#export MIGASFREE_VERSION=master
#export MIGASFREE_VERSION=latest

export MIGASFREE_PORT=80

export POSTGRES_PORT=5432

export POSTGRES_DB=migasfree
export POSTGRES_USER=migasfree
export POSTGRES_PASSWORD=migasfree

export POSTGRES_CRON="00 00 * * *"

#export POSTGRES_ALLOW_HOSTS="192.168.92.0/24"
export POSTGRES_ALLOW_HOSTS=""

export TZ=Europe/Madrid

export http_proxy=
export https_proxy=
